const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA=path.join(ROOT,'data'),DB=path.join(DATA,'data.json'),UPLOADS=path.join(DATA,'uploads');
fs.mkdirSync(UPLOADS,{recursive:true});
const demoWorkers=[
['Ramesh Kumar','Mason',8,'Gurugram',100,750,4.8,124,'Verified'],['Suresh Yadav','Painter',6,'Gurugram',110,800,4.7,91,'Verified'],['Amit Kumar','Electrician',5,'Delhi',120,900,4.9,76,'Verified'],['Rajesh','Plumber',7,'Gurugram',115,850,4.6,68,'Verified'],['Mohan Singh','Carpenter',9,'Manesar',135,1000,4.8,83,'Verified'],['Deepak','Welder',4,'Gurugram',125,950,4.7,52,'Verified']
].map(x=>({id:crypto.randomUUID(),name:x[0],category:x[1],experience:x[2],location:x[3],hourly_rate:x[4],daily_rate:x[5],rating:x[6],reviews:x[7],verification_status:x[8],status:x[8],availability:'Available',skills:'Skilled professional',documents:[],createdAt:new Date().toISOString()}));
const initial={users:[],workers:demoWorkers,customers:[],jobs:[],requests:[]};
function load(){if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(initial,null,2));try{const d=JSON.parse(fs.readFileSync(DB,'utf8'));d.users??=[];d.workers??=[];d.customers??=[];d.jobs??=d.requests||[];d.requests??=d.jobs||[];return d}catch{return structuredClone(initial)}}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function json(res,status,o){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Cache-Control':'no-store'});res.end(JSON.stringify(o))}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>30e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
function hash(p,s){return crypto.scryptSync(String(p),s,64).toString('hex')};function pass(p){const s=crypto.randomBytes(16).toString('hex');return{salt:s,hash:hash(p,s)}};function verify(p,r){try{return crypto.timingSafeEqual(Buffer.from(hash(p,r.salt),'hex'),Buffer.from(r.hash,'hex'))}catch{return false}}
const sessions=new Map();function token(req){const h=req.headers.authorization||'';return h.startsWith('Bearer ')?h.slice(7):''};function user(req){const id=sessions.get(token(req));return id?load().users.find(x=>x.id===id):null};function admin(req){const u=user(req);return u&&u.role==='admin'}
function seedAdmin(){const e=process.env.ADMIN_EMAIL,p=process.env.ADMIN_PASSWORD;if(!e||!p)return;const d=load();if(!d.users.some(u=>u.role==='admin')){const pr=pass(p);d.users.push({id:crypto.randomUUID(),name:'Manav Arora',email:e,mobile:'',role:'admin',password:pr});save(d)}}seedAdmin();
function sendFile(res,f){const ext=path.extname(f),types={'.html':'text/html; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.js':'text/javascript','.css':'text/css','.pdf':'application/pdf'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}
function saveDataUrl(workerId,doc){if(!doc||!doc.dataUrl||!doc.name)return null;const m=String(doc.dataUrl).match(/^data:([^;]+);base64,(.+)$/);if(!m)return null;const buf=Buffer.from(m[2],'base64');if(buf.length>8e6)return null;const id=crypto.randomUUID(),ext=path.extname(doc.name).replace(/[^\w.]/g,'').slice(0,8)||'.bin',stored=`${workerId}-${id}${ext}`;fs.writeFileSync(path.join(UPLOADS,stored),buf);return{id,originalName:doc.name,mime:m[1],size:buf.length,storedName:stored,uploadedAt:new Date().toISOString()}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});const u=new URL(req.url,`http://${req.headers.host}`),p=u.pathname;try{
if(req.method==='GET'&&p==='/api/workers'){const d=load(),q=u.searchParams;let w=d.workers;if(q.get('category'))w=w.filter(x=>x.category===q.get('category'));if(q.get('location'))w=w.filter(x=>(x.location||'').toLowerCase().includes(q.get('location').toLowerCase()));if(q.get('status'))w=w.filter(x=>(x.verification_status||x.status)===q.get('status'));return json(res,200,w)}
if(req.method==='GET'&&p==='/api/customers')return json(res,200,load().customers);
if(req.method==='GET'&&p==='/api/requests')return json(res,200,load().jobs);
if(req.method==='POST'&&p==='/api/auth/register'){const x=await body(req),d=load();if(!x.name||!x.mobile||!x.password||!x.role)return json(res,400,{error:'Required registration fields are missing'});if(d.users.some(z=>z.mobile===x.mobile||(x.email&&z.email===x.email)))return json(res,409,{error:'An account with this mobile/email already exists'});const id=crypto.randomUUID(),pr=pass(x.password),u={id,name:x.name,mobile:x.mobile,email:x.email||'',role:x.role,password:pr,createdAt:new Date().toISOString()};d.users.push(u);if(x.role==='worker'){const w={id:crypto.randomUUID(),user_id:id,name:x.name,mobile:x.mobile,email:x.email||'',category:x.category||'Other',skills:x.skills||'',experience:Number(x.experience)||0,location:x.location||'',hourly_rate:Number(x.hourly_rate)||0,daily_rate:Number(x.daily_rate)||0,bio:x.bio||'',address:x.address||'',availability:x.availability||'Available',rating:5,reviews:0,verification_status:'Pending',status:'Pending',photo:x.profilePhoto?.dataUrl||null,documents:[],createdAt:new Date().toISOString()};if(Array.isArray(x.documents))for(const q of x.documents.slice(0,5)){const saved=saveDataUrl(w.id,q);if(saved)w.documents.push(saved)}d.workers.unshift(w);u.worker_id=w.id}else{const c={id:crypto.randomUUID(),user_id:id,name:x.name,mobile:x.mobile,email:x.email||'',location:x.location||'',address:x.address||'',jobs:0,status:'Active',createdAt:new Date().toISOString()};d.customers.unshift(c);u.customer_id=c.id}save(d);const t=crypto.randomBytes(32).toString('hex');sessions.set(t,id);return json(res,201,{token:t,user:{id:u.id,name:u.name,mobile:u.mobile,email:u.email,role:u.role,worker_id:u.worker_id,customer_id:u.customer_id}})}
if(req.method==='POST'&&p==='/api/auth/login'){const x=await body(req),d=load(),u=d.users.find(z=>(z.mobile===x.identifier||z.email===x.identifier)&&z.role!==undefined);if(!u||!verify(x.password,u.password))return json(res,401,{error:'Invalid login details'});const t=crypto.randomBytes(32).toString('hex');sessions.set(t,u.id);return json(res,200,{token:t,user:{id:u.id,name:u.name,mobile:u.mobile,email:u.email,role:u.role,worker_id:u.worker_id,customer_id:u.customer_id}})}
if(req.method==='GET'&&p==='/api/me'){const u=user(req);if(!u)return json(res,401,{error:'Unauthorized'});const d=load();let profile=u.role==='worker'?d.workers.find(w=>w.id===u.worker_id):d.customers.find(c=>c.id===u.customer_id);return json(res,200,{user:{id:u.id,name:u.name,mobile:u.mobile,email:u.email,role:u.role},profile:profile||null})}
if(req.method==='POST'&&p==='/api/jobs'){const u=user(req);if(!u||u.role!=='customer')return json(res,401,{error:'Customer login required'});const x=await body(req),d=load(),w=d.workers.find(z=>z.id===x.worker_id);if(!w)return json(res,404,{error:'Worker not found'});const j={id:crypto.randomUUID(),customer_id:u.customer_id,customer_name:u.name,worker_id:w.id,worker_name:w.name,title:x.title||'Work request',description:x.description||'',location:x.location||'',work_date:x.work_date||'',duration_hours:Number(x.duration_hours)||1,agreed_amount:Number(x.agreed_amount)||0,status:'Pending',payment_status:'Unpaid',createdAt:new Date().toISOString()};d.jobs.unshift(j);d.requests=d.jobs;save(d);return json(res,201,j)}
if(req.method==='GET'&&p==='/api/jobs'){const u=user(req);if(!u)return json(res,401,{error:'Login required'});const d=load();let j=d.jobs;if(u.role==='customer')j=j.filter(x=>x.customer_id===u.customer_id);if(u.role==='worker')j=j.filter(x=>x.worker_id===u.worker_id);return json(res,200,j)}
if(req.method==='PATCH'&&p.startsWith('/api/jobs/')){const u=user(req);if(!u)return json(res,401,{error:'Login required'});const id=p.split('/').pop(),x=await body(req),d=load(),j=d.jobs.find(z=>z.id===id);if(!j)return json(res,404,{error:'Job not found'});if(u.role==='worker'&&j.worker_id!==u.worker_id||u.role==='customer'&&j.customer_id!==u.customer_id)return json(res,403,{error:'Not allowed'});j.status=x.status||j.status;d.requests=d.jobs;save(d);return json(res,200,j)}
if(req.method==='POST'&&p==='/api/payments/demo'){const u=user(req);if(!u||u.role!=='customer')return json(res,401,{error:'Customer login required'});const x=await body(req),d=load(),j=d.jobs.find(z=>z.id===x.job_id&&z.customer_id===u.customer_id);if(!j)return json(res,404,{error:'Job not found'});j.payment_status='Paid';save(d);return json(res,200,j)}
if(req.method==='POST'&&p==='/api/workers/kyc'){const u=user(req);if(!u||u.role!=='worker')return json(res,401,{error:'Worker login required'});const x=await body(req),d=load(),w=d.workers.find(z=>z.id===u.worker_id);if(!w)return json(res,404,{error:'Worker not found'});const doc=saveDataUrl(w.id,x.document);if(!doc)return json(res,400,{error:'Invalid document or file too large'});w.documents=w.documents||[];w.documents.push(doc);w.verification_status='Pending';w.status='Pending';save(d);return json(res,201,doc)}
if(req.method==='GET'&&p==='/api/admin/workers'){if(!admin(req))return json(res,401,{error:'Admin authentication required'});return json(res,200,load().workers)}
if(req.method==='POST'&&p==='/api/admin/login'){const x=await body(req),d=load(),a=d.users.find(z=>z.role==='admin'&&z.email===x.email);if(!a||!verify(x.password,a.password))return json(res,401,{error:'Invalid admin credentials'});const t=crypto.randomBytes(32).toString('hex');sessions.set(t,a.id);return json(res,200,{token:t,user:{name:a.name,role:'admin'}})}
if(req.method==='GET'&&p.startsWith('/api/admin/documents/')){if(!admin(req))return json(res,401,{error:'Admin authentication required'});const [_,__,___,____,wid,did]=p.split('/'),d=load(),w=d.workers.find(z=>z.id===wid),doc=w?.documents?.find(z=>z.id===did);if(!doc)return json(res,404,{error:'Document not found'});const file=path.join(UPLOADS,doc.storedName);if(!fs.existsSync(file))return json(res,404,{error:'File not found'});res.writeHead(200,{'Content-Type':doc.mime||'application/octet-stream','Content-Disposition':'inline; filename="'+doc.originalName.replace(/"/g,'')+'"'});fs.createReadStream(file).pipe(res);return}
if(req.method==='PATCH'&&p.startsWith('/api/workers/')){if(!admin(req))return json(res,401,{error:'Admin authentication required'});const id=decodeURIComponent(p.slice('/api/workers/'.length)),d=load(),x=await body(req),w=d.workers.find(z=>z.id===id||z.name===id);if(!w)return json(res,404,{error:'Worker not found'});Object.assign(w,x);if(x.status==='Verified'||x.verification_status==='Verified'){w.status='Verified';w.verification_status='Verified'}save(d);return json(res,200,w)}
if(req.method==='GET'){if(p==='/'||p==='/index.html')return sendFile(res,path.join(PUBLIC,'index.html'));if(p==='/admin'||p==='/admin.html')return sendFile(res,path.join(PUBLIC,'admin.html'));const f=path.normalize(path.join(PUBLIC,p.replace(/^\/+/,'')));if(f.startsWith(PUBLIC)&&fs.existsSync(f)&&fs.statSync(f).isFile())return sendFile(res,f)}
return json(res,404,{error:'Not found'})}catch(e){console.error(e);return json(res,500,{error:'Server error',detail:process.env.NODE_ENV==='production'?undefined:e.message})}});
server.listen(PORT,()=>console.log(`Digital Thekedaar running at http://localhost:${PORT}`));
